require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AuthTablesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AuthTable. As you add validations to AuthTable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthTablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all auth_tables as @auth_tables" do
      auth_table = AuthTable.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:auth_tables)).to eq([auth_table])
    end
  end

  describe "GET show" do
    it "assigns the requested auth_table as @auth_table" do
      auth_table = AuthTable.create! valid_attributes
      get :show, {:id => auth_table.to_param}, valid_session
      expect(assigns(:auth_table)).to eq(auth_table)
    end
  end

  describe "GET new" do
    it "assigns a new auth_table as @auth_table" do
      get :new, {}, valid_session
      expect(assigns(:auth_table)).to be_a_new(AuthTable)
    end
  end

  describe "GET edit" do
    it "assigns the requested auth_table as @auth_table" do
      auth_table = AuthTable.create! valid_attributes
      get :edit, {:id => auth_table.to_param}, valid_session
      expect(assigns(:auth_table)).to eq(auth_table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AuthTable" do
        expect {
          post :create, {:auth_table => valid_attributes}, valid_session
        }.to change(AuthTable, :count).by(1)
      end

      it "assigns a newly created auth_table as @auth_table" do
        post :create, {:auth_table => valid_attributes}, valid_session
        expect(assigns(:auth_table)).to be_a(AuthTable)
        expect(assigns(:auth_table)).to be_persisted
      end

      it "redirects to the created auth_table" do
        post :create, {:auth_table => valid_attributes}, valid_session
        expect(response).to redirect_to(AuthTable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved auth_table as @auth_table" do
        post :create, {:auth_table => invalid_attributes}, valid_session
        expect(assigns(:auth_table)).to be_a_new(AuthTable)
      end

      it "re-renders the 'new' template" do
        post :create, {:auth_table => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested auth_table" do
        auth_table = AuthTable.create! valid_attributes
        put :update, {:id => auth_table.to_param, :auth_table => new_attributes}, valid_session
        auth_table.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested auth_table as @auth_table" do
        auth_table = AuthTable.create! valid_attributes
        put :update, {:id => auth_table.to_param, :auth_table => valid_attributes}, valid_session
        expect(assigns(:auth_table)).to eq(auth_table)
      end

      it "redirects to the auth_table" do
        auth_table = AuthTable.create! valid_attributes
        put :update, {:id => auth_table.to_param, :auth_table => valid_attributes}, valid_session
        expect(response).to redirect_to(auth_table)
      end
    end

    describe "with invalid params" do
      it "assigns the auth_table as @auth_table" do
        auth_table = AuthTable.create! valid_attributes
        put :update, {:id => auth_table.to_param, :auth_table => invalid_attributes}, valid_session
        expect(assigns(:auth_table)).to eq(auth_table)
      end

      it "re-renders the 'edit' template" do
        auth_table = AuthTable.create! valid_attributes
        put :update, {:id => auth_table.to_param, :auth_table => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested auth_table" do
      auth_table = AuthTable.create! valid_attributes
      expect {
        delete :destroy, {:id => auth_table.to_param}, valid_session
      }.to change(AuthTable, :count).by(-1)
    end

    it "redirects to the auth_tables list" do
      auth_table = AuthTable.create! valid_attributes
      delete :destroy, {:id => auth_table.to_param}, valid_session
      expect(response).to redirect_to(auth_tables_url)
    end
  end

end
